# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(348, 317)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_um = QtWidgets.QPushButton(self.centralwidget)
        self.btn_um.setGeometry(QtCore.QRect(40, 230, 56, 31))
        self.btn_um.setObjectName("btn_um")
        self.btn_dois = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dois.setGeometry(QtCore.QRect(100, 230, 56, 31))
        self.btn_dois.setObjectName("btn_dois")
        self.btn_tres = QtWidgets.QPushButton(self.centralwidget)
        self.btn_tres.setGeometry(QtCore.QRect(160, 230, 56, 31))
        self.btn_tres.setObjectName("btn_tres")
        self.btn_quatro = QtWidgets.QPushButton(self.centralwidget)
        self.btn_quatro.setGeometry(QtCore.QRect(40, 190, 56, 31))
        self.btn_quatro.setObjectName("btn_quatro")
        self.txt_input = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_input.setEnabled(False)
        self.txt_input.setGeometry(QtCore.QRect(40, 30, 261, 31))
        self.txt_input.setObjectName("txt_input")
        self.btn_cinco = QtWidgets.QPushButton(self.centralwidget)
        self.btn_cinco.setGeometry(QtCore.QRect(100, 190, 56, 31))
        self.btn_cinco.setObjectName("btn_cinco")
        self.btn_seis = QtWidgets.QPushButton(self.centralwidget)
        self.btn_seis.setGeometry(QtCore.QRect(160, 190, 56, 31))
        self.btn_seis.setObjectName("btn_seis")
        self.btn_sete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sete.setGeometry(QtCore.QRect(40, 150, 56, 31))
        self.btn_sete.setObjectName("btn_sete")
        self.btn_oito = QtWidgets.QPushButton(self.centralwidget)
        self.btn_oito.setGeometry(QtCore.QRect(100, 150, 56, 31))
        self.btn_oito.setObjectName("btn_oito")
        self.btn_nove = QtWidgets.QPushButton(self.centralwidget)
        self.btn_nove.setGeometry(QtCore.QRect(160, 150, 56, 31))
        self.btn_nove.setObjectName("btn_nove")
        self.btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_zero.setGeometry(QtCore.QRect(100, 270, 56, 31))
        self.btn_zero.setObjectName("btn_zero")
        self.btn_ponto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ponto.setGeometry(QtCore.QRect(40, 270, 56, 31))
        self.btn_ponto.setObjectName("btn_ponto")
        self.btn_igual = QtWidgets.QPushButton(self.centralwidget)
        self.btn_igual.setGeometry(QtCore.QRect(160, 270, 56, 31))
        self.btn_igual.setFlat(False)
        self.btn_igual.setObjectName("btn_igual")
        self.btn_sub = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sub.setGeometry(QtCore.QRect(220, 230, 56, 31))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.btn_mult.setGeometry(QtCore.QRect(220, 190, 56, 31))
        self.btn_mult.setObjectName("btn_mult")
        self.btn_div = QtWidgets.QPushButton(self.centralwidget)
        self.btn_div.setGeometry(QtCore.QRect(220, 150, 56, 31))
        self.btn_div.setObjectName("btn_div")
        self.btn_soma = QtWidgets.QPushButton(self.centralwidget)
        self.btn_soma.setGeometry(QtCore.QRect(220, 270, 56, 31))
        self.btn_soma.setObjectName("btn_soma")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_um.setText(_translate("MainWindow", "1"))
        self.btn_dois.setText(_translate("MainWindow", "2"))
        self.btn_tres.setText(_translate("MainWindow", "3"))
        self.btn_quatro.setText(_translate("MainWindow", "4"))
        self.btn_cinco.setText(_translate("MainWindow", "5"))
        self.btn_seis.setText(_translate("MainWindow", "6"))
        self.btn_sete.setText(_translate("MainWindow", "7"))
        self.btn_oito.setText(_translate("MainWindow", "8"))
        self.btn_nove.setText(_translate("MainWindow", "9"))
        self.btn_zero.setText(_translate("MainWindow", "0"))
        self.btn_ponto.setText(_translate("MainWindow", "."))
        self.btn_igual.setText(_translate("MainWindow", "="))
        self.btn_sub.setText(_translate("MainWindow", "-"))
        self.btn_mult.setText(_translate("MainWindow", "*"))
        self.btn_div.setText(_translate("MainWindow", "/"))
        self.btn_soma.setText(_translate("MainWindow", "+"))
